version: '3.1'

services:
  db:
    image: mysql:8.0.35
    volumes:
      - dbase:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: exptracker_db
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8000:80

volumes:
  dbase: