version: '3.7'

services:
  mysql:
    image: mysql:latest
    container_name: exp_mysql_db
    environment:
      MYSQL_DATABASE: exptracker_db
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - dbase:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - db_network

  redis:
    image: redis:latest
    container_name: exp_redis_server
    ports:
      - "6379:6379"
    networks:
      - db_network

volumes:
  dbase:
    driver: local

networks:
  db_network:
    driver: bridge
